Algoritmo "desconto"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/09/2024
Var
// Seção de Declarações das variáveis 
    desconto, preco:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

    escreval("qual o preço da compra")
    leia(preco)
    
    desconto<- preco * 0.90
    
    escreval("com o desconto fica", desconto)
    
    

Fimalgoritmo