Algoritmo "dobro e a terça parte"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2024
Var
// Seção de Declarações das variáveis 
  num: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval("Digite um numero ")
  leia(num)
  
  escreval("a terca parte é:", num / 3 ,"  e o seu dobro é:", num * 2)
Fimalgoritmo