Algoritmo "km_metros"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/09/2024
Var
// Seção de Declarações das variáveis 
    km, metros: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreval("digite a quantidade de km")
     leia(km)
     
     metros <- km * 1000

     escreval ("o resultado é:", metros," ","metros")

Fimalgoritmo