Algoritmo "reais e dolares"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2024
Var
// Seção de Declarações das variáveis 
  rs, dolar: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("quantos Reais a pessoa tem na carteira?")
   leia(rs)
   
   dolar<- rs * 5.45
   
   escreval("R$:",rs ,"  pode ser trocado por $", dolar:5:2)

Fimalgoritmo