Algoritmo "sfuncionario"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2024
Var
// Seção de Declarações das variáveis 
  diast, sfuncionario: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("quantas horas foram trabalhadas?")
   leia(diast)
   
   sfuncionario<- diast * 4
   
   escreval("o salario do funcionario deve ser:", sfuncionario)
   
Fimalgoritmo