Algoritmo "voto"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/09/2024
Var
// Seção de Declarações das variáveis 
 anon, votar: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  escreval("Qual ano você nasceu?")
  leia(anon)
  
  se anon < 2008  entao
     escreval("você pode votar")
  senao
     escreval("voce não pode votar")

  fimse

Fimalgoritmo